apiVersion: v1
kind: Service
metadata:
  name: mlops-savings-service
spec:
  type: LoadBalancer
  selector:
    app: mlops-savings-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
